#!/bin/bash

if  grep "kAccelerometerFrequency.*60\\." "$1"/Classes/AppController.mm ; then
	/usr/bin/perl -p -i -e "s/kAccelerometerFrequency.*60/kAccelerometerFrequency\t\t\t\t\t1/g" "$1"/Classes/AppController.mm 
fi 

