/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EOPENIAB_AUTODEFS_H
#define S3EOPENIAB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_OPENIAB_NAME "s3eOpenIab"
#define S3E_EXT_OPENIAB_HASH 0xde54774e

#endif /* !S3EOPENIAB_AUTODEFS_H */
